workflows:
  ios-cert-generator:
    name: Generate iOS Certificate
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Generate certificate
        script: |
          echo "Certificate generation step"

    artifacts:
      - $HOME/Library/MobileDevice/Certificates/*.p12
      - $HOME/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision