workflows:
  ios-release:
    name: iOS Signed Build
    max_build_duration: 60

    integrations:
      app_store_connect:
        - CodemagicKey

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cybrains.scamkavatchpro

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        submit_to_testflight: true