workflows:
  ios-cert-generator:
    name: Generate iOS Certificate
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Generate signing certificate
        script: |
          mkdir -p $HOME/certs
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings build.keychain

          security find-identity -v

    artifacts:
      - $HOME/certs/*.p12
      - $HOME/certs/*.mobileprovision