workflows:
  ios-release:
    name: iOS Signed Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

      groups:
        - APP_STORE_CONNECT

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build signed IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa