workflows:
  ios-release:
    name: iOS Signed IPA Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cybrains.scamkavatchpro

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Configure signing
        script: xcode-project use-profiles

      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa