workflows:
  ios-release:
    name: iOS Signed IPA Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cybrains.scamkavatchpro

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build IPA with signing
        script: |
          xcode-project use-profiles
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa