C:\flutter_projects\scam_kavatch_pro_IOS_1>git commit -m "Add iOS auto upload workflow"
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   pubspec.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        main
        pip

no changes added to commit (use "git add" and/or "git commit -a")

C:\flutter_projects\scam_kavatch_pro_IOS_1>git push
Everything up-to-date

C:\flutter_projects\scam_kavatch_pro_IOS_1>