workflows:
  ios-release:
    name: iOS Release Build

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cybrains.scamkavatchpro

    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --build-name=1.0.56 \
            --build-number=63

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        apple_id: "r_raina27@yahoo.co.in"
        app_specific_password: $APP_SPECIFIC_PASSWORD
        submit_to_testflight: true